#!/usr/bin/groovy
@Library('PsObaiLib')_
 
try {
    node {
        stage '\u2777 Clean Up'
        
		stage ('\u2777 Checkout') {
			CheckOut(["https://github.com/areshdeep/TestRepository"])
		}
		stage ('\u2777 Build') {
		}
        
        stage '\u2777 Tesing'
        
        stage '\u2777 Deploy'
        
        stage '\u2777 SonarQube Analysis'
    }
} 
catch (exc) {
    print exc
} 