#!/usr/bin/groovy
@Library('PsObaiLib')_
 
try {
    node {
        stage '\u2777 Clean Up'
		{
			properties([parameters([booleanParam(defaultValue: false, description: '', name: 'DeploymentParameterTest')])])
            if (DeploymentParameterTest)
            {
                echo "Test success"
            }
            else
            {
                echo "Test failure"   
            }
		}
        
		stage ('\u2777 Checkout') {
			// checkoutUrl(["https://github.com/areshdeep/TestRepository"])
		}
		stage ('\u2777 Build') {
		}
        
        stage '\u2777 Tesing'
        
        stage '\u2777 Deploy'
        
        stage '\u2777 SonarQube Analysis'
    }
} 
catch (exc) {
    print exc
} 